#mybatis
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/task7?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: usertwo
    password: 456123..
    driver-class-name: com.mysql.jdbc.Driver

  thymeleaf:
    cache: false
    mode: LEGACYHTML5

mybatis-plus:
#  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath*:/mapper/*.xml
#  type-aliases-package: com.lihoo.jnshu.common.domain
  type-aliases-super-type: java.lang.Object
#  type-handlers-package: com.lihoo.jnshu.handler
  check-config-location: false
  executor-type: simple
#  configuration-properties: classpath:mybatis/config.properties
#  configuration:
#      aggressive-lazy-loading: true
#      auto-mapping-unknown-column-behavior: none
#      auto-mapping-behavior: partial
#      cache-enabled: true
#      call-setters-on-nulls: false
#      configuration-factory: com.xxx.SampleConfigurationFactory
  global-config:
      db-config:
        capital-mode: false
        column-like: false
        db-type: mysql
        id-type: id_worker
        logic-delete-value: 1
        logic-not-delete-value: 0
#